# Generated by Django 2.2.6 on 2019-12-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verbindung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('favorit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField()),
                ('ende', models.TextField()),
                ('position', models.IntegerField()),
                ('verbindung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bahn.Verbindung')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abfahrt', models.DateTimeField()),
                ('ankunft', models.DateTimeField()),
                ('verspaetung', models.IntegerField()),
                ('typ', models.TextField()),
                ('gleis', models.TextField()),
                ('zielbahnhof', models.TextField()),
                ('nummer', models.TextField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bahn.Segment')),
            ],
        ),
    ]
