# Generated by Django 2.2.6 on 2020-01-09 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bahn', '0002_auto_20191218_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrt',
            name='zeit',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
