# Generated by Django 2.2.6 on 2020-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahn', '0003_fahrt_zeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrt',
            name='zeit',
            field=models.TextField(),
        ),
    ]
