# Generated by Django 2.2.6 on 2020-01-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahn', '0004_auto_20200109_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrt',
            name='rueckweg',
            field=models.BooleanField(default=False),
        ),
    ]
